### ISSUE TITLE
Multiple versions of the same image when original asset isn't large enough

### ISSUE THREAD

**Issue by terryupton** [aelvan/Imager-Craft#59] opened 2016-11-09 22:13 UTC
When using the Imager plugin and creating responsive images using srcset and sizes? Any ideas on how to avoid creating multiple versions of the same image if the original asset uploaded is smaller than the set transforms? I added the setting 'allowUpscale'       =>      false, but this has resulted in 7 versions of the same image (same dimensions etc)

~~~
/imager/resources/general/359/Golden-Retriever-Isolated_b4a9cbfcf0e16c2bbe8891faf2f17377.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_46442a24ab3b20705cf025765c954564.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_dc3d89e10897fe49613e23ec867b72c7.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_13d85085a2b68d4289e86166bdc76d2f.jpg 302w,
/imager/resources/general/359/Golden-Retriever-Isolated_033ae678b7fe3957fc7ac9eab98c2dac.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_78f5cce99e1c3c7765fb260eb99fceaa.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_3907e8c0ed1757af4be1f9f097fb579b.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_6e4e16791425f7dfc1ab06a09cd800f4.jpg 302w, 
/imager/resources/general/359/Golden-Retriever-Isolated_042ca14a1382a40b78a83ee7d3f8e3dd.jpg 300w
~~~

Here is my code for reference:

~~~
{% case "image" %}
{% set image = block.image.first() %}
{% set transformedImages = craft.imager.transformImage(image, [
        { width: 1680 },
        { width: 1430 },
        { width: 1350 },
        { width: 1150 },
        { width: 840 },
        { width: 715 },
        { width: 660 },
        { width: 450},
        { width: 300}
    ], { mode: 'fit' })
%}
<figure{%- if block.position != "full" %} class="img-{{ block.position }}--small"{% endif -%}>
    <img
        src="{{ craft.imager.transformImage(image, { width: 715, mode: 'fit' }) }}"
        srcset="{{ craft.imager.srcset(transformedImages) }}"
        sizes="{{ (block.position == 'full') ? '(max-width: 60em) 100vw, 61.5vw' : '(max-width: 37.5em) 100vw, (max-width: 81.25em) 30vw, 400px'  }}"
        alt="{{ image.altText ?: image.title }}"
    />
    {% if block.caption|length %}
    <figcaption class="figcaption">
        {{ block.caption }}
    </figcaption>
    {% endif %}
</figure>
~~~

**Comment by aelvan** [comment] 2016-12-29 20:53
This proved to be a particulary tricky problem to solve. 

The filename is created based on the transform string passed in, which is why the filenames are different, while the size being the same. The filename has to be created before the image is opened, because opening the image is a resource intensive operation which would seriously decrease performance.  

Trying to figure out if the image needed to be created without opening it is possible, except, you want to create one image that has the maximum possible size. The problem is knowing if this has been created or not. Creating multiple images in one Imager method call, that creates several images that have the exact same size, is a completely valid use-case. So, actually knowing if the transform created different images or not isn't simple.

Anyways, creating different duplicate images have two problems; 1) it wastes disk-space, and 2) it makes the browser load more images than necessary when used as a srcset.

Disk-space isn't really a concern I had when creating Imager, the whole point was to make something file-based that was optimized for speed. 

The second issue is a more serious issue. To counter this, I've implemented a fix in the `craft.imager.srcset` template variable that only outputs sizes that haven't already been output, since it never makes sense to have several images with the same width in an srcset. This will be included in the next version of Imager.

So, that fixes 2) but not 1). I'll have this in mind when I (have to) refactor Imager for Craft 3, but for now I won't do anything more in regards to this.

**Closed by aelvan** 2016-12-29 20:53 UTC
