### ISSUE TITLE
getimagesize(): Read error!

### ISSUE THREAD

**Issue by katrinkerber** [aelvan/Imager-Craft#14] opened 2016-01-12 18:33 UTC
I am trying to transform video thumbnails which I retrieve via the Embedder plugin, but am running into an odd issue.

This is my code:
````
{% set videoEmbedderUrl = item.videoUrl|replace({'youtube.com/embed/': 'youtube.com/watch?v='}) %}
{% set videoEmbedderElement = craft.embedder.url(videoEmbedderUrl) %}
{% set videoThumb = videoEmbedderElement.video_highres|replace('https', 'http') %}

{% set videoThumbCroppedUrl = '' %}
{% set videoThumbCropped = craft.imager.transformImage(videoThumb, [{ ratio: 3/2 }]) %}
{% for videoThumbCropped in videoThumbCropped %}
  {% set videoThumbCroppedUrl = videoThumbCropped.getUrl() %}
{% endfor %}
````

This works great for a lot of the videos, but some of them cause this error:
````
getimagesize(): Read error!
````

When I print out `{{ videoThumb }}` the correct URL is shown and the external image definitely exists as well. I can also see the transform folder for that image having been generated on the server, but no image inside of it.

What could be causing this issue?

**Comment by aelvan** [comment] 2016-01-12 18:35
Can you post the url to an image that fails? Might have something to do with the filename? Only thing I can think of right now.

**Comment by katrinkerber** [comment] 2016-01-12 18:37
Of course: `http://i.ytimg.com/vi/16_kvQ0YYAI/sddefault.jpg`

**Comment by aelvan** [comment] 2016-01-12 18:46
That's weird, I tested it now with that image, and it works just fine. Which image driver are you using? Does the error reference the line it's on (if you run in devMode)? Does it happend on the same images all the time? Like, does it seem to be related to specific images, or is it more random?

**Comment by katrinkerber** [comment] 2016-01-12 19:04
Huh, you are right. On the remote server all the images work, it's just on my local install that I get that message. Maybe it has to do with the image driver, I am not sure if Mamp Pro comes with Imagick...

Below the error it references this file and line:
`/craft/app/services/ImagesService.php(142)`

Also, on the remote server the `craft.imager.transformImage(videoThumb, [{ ratio: 3/2 }])` wasn't working and was returning the images in their original size and ratio. I had to explicitly state the width and height for this to work like so `craft.imager.transformImage(videoThumb, [{ width: 640, height: 428 }])`, which is fine, but thought it might be something you want to check :)

**Comment by aelvan** [comment] 2016-01-12 19:57
Mamp Pro comes with both, but Imagick isn't enabled by default. I've tested both GD and Imagick though, and both works for me. 

The error message is actually from Craft's ImageService, but I guess it's called from ImagerService. Could you check, just to be sure, that Imager is referenced in the stack trace? And which file+line in ImagerService it references?

There's a bug (or, "an oversight" would be more correct) where the image won't be resized if only ratio is given, and no width or height. I'll add a fix for that in the next release.

**Comment by katrinkerber** [comment] 2016-01-13 10:54
Here a screenshot of the error: 
![imager-error](https://cloud.githubusercontent.com/assets/818635/12292264/d5cdba5e-b9e3-11e5-9918-e7fbfac0c667.png)

Hope you can make sense of this, it's all gobbledygook to me :)

**Comment by dennisfrank** [comment] 2016-01-13 13:19
I get exactly the same error on a server. Works perfectly under MAMP.

**Comment by aelvan** [comment] 2016-01-13 13:34
@dennisfrank Is this also on a remote image? And does it happen all the time, for some specific images only, or completely random?

**Comment by dennisfrank** [comment] 2016-01-13 13:35
This is what my Imager variable looks like: 

    {% set blogTeaserImage = craft.imager.transformImage(externalBlogTeaserImageUrl,
      {
        width: 400,
        height: 400,
        hashRemoteUrl: true
      }) %}


My Imager config:

```
return array(
  'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/images/sized/',
  'imagerUrl' => '/images/sized/',
  'hashFilename' => 'postfix', // true, false, or 'postfix' (meaning only the generated part of the filename is hashed)
  'hashRemoteUrl' => 'host', // true, false, or 'host' (meaning only the host part of the url is hashed)
);
```


The image shows up in `craft/storage/runtime/imager`:

    craft/storage/runtime/imager/bcd09c8d88/image.jpg

But its size is 0 bytes!

**Comment by dennisfrank** [comment] 2016-01-13 13:37
@aelvan Yes. This happens all the time on remote images.

**Comment by aelvan** [comment] 2016-01-13 13:42
@dennisfrank Can you check what the permissions on the file/folder is? When you say that it happends "all the time", do you mean that it happends for every single remote image you try to transform? Or just.. "often"?

**Comment by dennisfrank** [comment] 2016-01-13 15:26
@aelvan It happens every time. I can not load pages with remote images transformed by Imager. 

I can't check the permissions right now. But I let you know later. Thanks for your time and support. Imager is such a great plugin!

**Comment by dennisfrank** [comment] 2016-01-14 17:08
@aelvan 

1. I checked the permissions and even changed it to 777 on `storage/runtime/imager`. Same error.

2. I tried it with local assets images (with and without `.getUrl()`). No problems so far and the images don’t stay as 0-byte files in `storage/runtime/imager`.

3. I tried different external images (jpg and png). Same error.

**Comment by dennisfrank** [comment] 2016-01-15 11:47
I got it working! :smiley:

`fopen` was disabled by the [host](https://df.eu) as a security measure.

I [enabled it with `allow_url_fopen = 1`](https://secure.php.net/manual/en/filesystem.configuration.php) in a custom `php.ini`.

@katrinkerber Can you make this change to your `php.ini`?

**Comment by gisu** [comment] 2016-01-18 00:22
Same here but `fopen` is active. On the local Mamp everything is fine, but on the Server i got this

`Unable to open image /www/htdocs/w007f580/designlovr.de/craft/storage/runtime/imager/designlovr_de/uploads/leadin/hero-v.jpg`

Storage have 777 (Imager put the Images in this folder), and have the Images inside. 

Imager Config
```php
<?php
return array(
  'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/uploads/imager/',
  'imagerUrl' => '/uploads/imager/'
);
```

**Comment by katrinkerber** [comment] 2016-01-18 14:59
`allow_url_fopen` were already set to `on` in both environments. 

I am now also having the same issue on the remote server, too :(

**Comment by katrinkerber** [comment] 2016-01-19 12:23
Thinking out loud: Could it be an upsizing error? Is Imager creating these 0KB empty images when the original image is smaller than the size set in the transform?

I think that may be the problem I am experiencing at my end.

**Comment by aelvan** [comment] 2016-01-19 13:22
Hi again. I don't think upsizing should have anything to do with this, the error occurs before Imager even tries to manipulate the image. The problem is that something fails during download, or/and when writing to the destination.

But, can you try replacing the file imager/models/Imager_ImagePathsModel.php with the one from the attached zip file? The download code was kind of sparse before, I've create a more solid routine that should at least give you some sensible error messages if something goes wrong. Also, if something goes wrong, before the zero-byte file would be in the cache and you would continue getting the error, even if the problem was fixed. The created file is now deleted if something goes wrong. So, make sure you empty the craft/storage/runtime/imager folder before you try again.

[Imager_ImagePathsModel.php.zip](https://github.com/aelvan/Imager-Craft/files/95923/Imager_ImagePathsModel.php.zip)

**Comment by katrinkerber** [comment] 2016-01-20 17:48
Thank you André.

I've replaced the file and cleared the `craft/storage/runtime/imager` folder. It certainly no longer creates a 0KB file, but it does still create the folder and the error has now changed to this:

![screen shot 2016-01-20 at 17 43 39](https://cloud.githubusercontent.com/assets/818635/12457705/01859f08-bf9e-11e5-805d-358af820c39b.png)

**Comment by aelvan** [comment] 2016-01-22 16:52
If I try to hit that url I also get a "404 Not Found" message. The browser shows an image, but the HTTP response code returned is 404. This is probably YouTube's way of saying that a thumb doesn't exist, but trying to be nice. Which mess up things in your end. ;)

But, I guess this, an image being returned as a 404, is a valid scenario, so I've implemented a small tweak to allow this. Can you try the new version of Imager_ImagePathsModel attached here. Same as last time, make sure you empty the cache for the remote files in the craft/storage/runtime/imager folder before testing again.

[Imager_ImagePathsModel.php.zip](https://github.com/aelvan/Imager-Craft/files/101139/Imager_ImagePathsModel.php.zip)

**Comment by aelvan** [comment] 2016-01-22 21:32
These improvements to remote images, and some more changes, are now available in version 1.0.2.

**Comment by katrinkerber** [comment] 2016-01-25 13:22
Thank you very much André, there are no more errors now :)

Yes, YouTube’s fallback when the thumbnail for a video doesn't exist is an odd one. I guess from my perspective it would be good if I could somehow implement a conditional which checks whether Imager was able to work with an image or not, and if not let’s me fallback to a placeholder image.

Would/Is something like this possible?

**Comment by katrinkerber** [comment] 2016-01-25 13:30
I could check the size of the fetched image, and if it is less 2KB I can assume it's YouTube’s placeholder thumbnail. Is there a way to get the retrieved image’s size? I can't find a note about it in the documentation.

**Comment by aelvan** [comment] 2016-01-25 14:44
Actually, I think this should be done in the step before this. It would be more natural if the Embedder plugin returned null or an empty string if the image wasn't found. Relying on the default YouTube image to be less than 2KB, and all the other images to be bigger, sounds a bit sketchy. :)

**Comment by katrinkerber** [comment] 2016-01-26 13:10
Yeah, I'm totally with you, just thinking of work-arounds. I'll leave a note on the Embedder side to see if there is a way to detect the YouTube placeholder image.

In the meantime, is there an Imager tag that can fetch the file size?

**Comment by aelvan** [comment] 2016-01-26 13:43
No, I haven't added that, but would be much work to add it to the model. I'll add it to the todo-list and let you know when I have implemented it.

**Comment by aelvan** [comment] 2016-01-27 10:21
Added size attribute and getSize() to the Imager_ImageModel model. Closing issue as the original issue has been sorted out. :)

**Closed by aelvan** 2016-01-27 10:21 UTC

**Comment by katrinkerber** [comment] 2016-01-27 13:45
Thank you so much André :)
