### ISSUE TITLE
Setting a bgColor appears to remove transparency from pngs

### ISSUE THREAD

**Issue by cholawo** [aelvan/Imager-Craft#281] opened 2019-10-15 10:31 UTC
It is  my understanding that the `bgColor` setting should only apply when pngs are converted to another format.
However, when I set `bgColor` to `#FFFFFF`, png files have their transparency removed even though they are output as png files.   When I remove that setting and regenerate the transforms I see correct transparency.   I've removed all other config to make sure it wasn't something else causing this to happen.
Any ideas?   I don't want to remove `bgColor` as I don't want some other transforms to be adversely affected (unless the default might end up being white anyway?).

**Comment by aelvan** [comment] 2019-10-15 10:53
This is the intended behavior. If `bgColor` is set, either through the config or as part of the transform, that color will be added as background color to transparent images.

**Comment by cholawo** [comment] 2019-10-15 11:01
@aelvan thanks for the quick reply, however that wasn't my interpretation of your docs:
"**If** an image is converted from a format that supports transparency, to a format that doesn't, you can specify which background color (in hexadecimal) the resulting image should have."
I thought this would mean the background color config is _only_ applied when an image is converted to a format _other_ than png.    I had thought perhaps sometimes my config might specify that an image must be converted to jpeg but other times let them remain a png, and that this `bgColor` setting only applied when imager converts it to jpeg.   If not then I can just throw away this `bgColor` config (it's a craft project I've inherited)

**Comment by aelvan** [comment] 2019-10-15 11:12
Right, that documentation probably needs to be updated. I think this changed at some point long ago, because the old behavior didn't make it possible to actually force a background color on an image with transparency. The way it is now you can do your own logic and pass in an empty string if you want to keep transparency for certain transforms.

**Comment by cholawo** [comment] 2019-10-15 12:41
Ok, thanks for the clarification!

**Comment by aelvan** [comment] 2020-02-11 19:34
Was fixed in the documentation for [Imager X](https://imager-x.spacecat.ninja/).

**Closed as completed by aelvan** 2020-02-11 19:34 UTC
Labels: bug, Documentation
